### ISSUE TITLE
Lijn Straelen - Herongen

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#1734]
Naam : Carlo<br/>Email : _Bekend bij de redactie_<br/>ID : [m63987](https://netkaart.hoogspanningsnet.com/balloon3.php?ID=m63987)<br/>Feedback tekst :<br/>====================<br/>Beste, ik heb SWK Netze GMBH gebeld en op de lijn Straelen - Herongen staat volgens hun 25 kV. Het schijnt een groot mysterie te zijn, daarom heb ik maar even gebeld. Het staat dus fout op de Hoogspanningsnetkaart
Groeten,, Venlo<br/>====================

**Comment by Kogacarlo** [comment]
Moderator, please delete the surname.
It's not supposed to be here.
Carlo

**Comment by HansNien** [comment]
_The surname is deleted, with apologies for the four days delay. We had some other busy issues since the calamity at Olsterpad and did not notice this over the weekend._

Voor het oorspronkelijke bericht, ik/we weten niet zeker meer waar die 30 kV vandaan is gekomen als getal. De klantaansluiting van die fabriek staat al jaren op de kaart en is ooit als 110 kV ingetekend, tot een Duitse cartograaf binnen ons team deze heeft aangepast naar 30 kV. Zo te horen/lezen na een telefoontje is 25 kV nu aannemelijker. Dank, we passen het per ommegaande aan op de kaart.
